const actionTypes={
    numberActions:{
      GET_NUMBER_START:"GET_NUMBER_START",
      GET_NUMBER_SUCCESS:" GET_NUMBER_SUCCESS",
      GET_NUMBER_FAIL:"GET_NUMBER_FAIL",
      DELETE_NUMBER_START:"DELETE_NUMBER_START",
      DELETE_NUMBER_SUCCESS:"DELETE_NUMBER_SUCCESS",
      DELETE_NUMBER_FAIL:"DELETE_NUMBER_FAIL",
      ADD_NUMBER:"ADD_NUMBER"
  },
  categoryActions:{
      GET_CATEGORIES_START:"GET_CATEGORIES_START",
      GET_CATEGORIES_SUCCESS:"GET_CATEGORIES_SUCCESS",
      GET_CATEGORIES_FAIL:"GET_CATEGORIES_FAIL",
  }
}

export default actionTypes